name: Deploy Lambda to AWS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -t python/
        cp lambda_function.py python/
        cd python && zip -r ../lambda.zip . && cd ..

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to Lambda (Create or Update)
      run: |
        set -e

        # Check if Lambda function exists
        if aws lambda get-function --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} 2>/dev/null; then
          echo "Lambda function exists. Updating code..."
          aws lambda update-function-code \
            --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
            --zip-file fileb://lambda.zip
        else
          echo "Lambda function does not exist. Creating function..."

          # Create IAM Role ARN with basic Lambda permissions beforehand and add to GitHub secrets
          aws lambda create-function \
            --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
            --runtime python3.11 \
            --role ${{ secrets.LAMBDA_ROLE_ARN }} \
            --handler lambda_function.lambda_handler \
            --zip-file fileb://lambda.zip \
            --timeout 30 \
            --memory-size 256
        fi
